### ISSUE TITLE
hwc.exe silently fails when missing dependencies

### ISSUE THREAD

**Issue by sneal** [cloudfoundry-incubator/hwc#1] opened 2017-02-28 19:39 UTC
This typically isn't something to worry about outside development since hwc.exe is typically only used from CloudFoundry which does a healthcheck for each app, but just in case...

1. Standup clean Windows box _without_ IIS or HWC installed. I'm using Windows 10 here, but other OSs likely exhibit similar behavior.
2. Install Web-WHC feature
3. Start a web application, e.g. `& { $env:PORT=8080; .\hwc.exe -appRootPath "C:\containerizer\env\ViewEnvironment\" }`

The stdout from hwc.exe displays something like:

```
Server Started for 41bd1a07-0909-41f1-9157-423a9e95cc14
```

However when browsing the site on port 8080, the browser cannot connect to the site. Looking at the Windows Application Event Log you'll notice a few errors:

```
The worker process failed to initialize correctly and therefore could not be started.  The data is the error.
The Module DLL C:\Windows\System32\inetsrv\validcfg.dll failed to load.  The data is the error.
```

Installing the IIS ASP.NET 4.6 feature along with it's dependencies and then restarting the hwc.exe produces a slightly different set of errors:

```
The worker process failed to initialize correctly and therefore could not be started.  The data is the error.
The Module DLL C:\Windows\System32\inetsrv\iiswsock.dll failed to load.  The data is the error.
```

Installing the WebSocket Protocol feature and restarting the hwc.exe process now properly starts the web server. There is a warning logged, but it the web server does work properly.

```
The directory specified for caching compressed content C:\Users\vagrant\tmp\IIS Temporary Compressed Files\AppPool9000 is invalid.  Static compression is being disabled.
```

**Comment by sunjayBhatia** [comment] 2017-03-01 00:36
@sneal We recently made some changes to the default directories that hwc uses so the last error makes sense, we need to maybe create that directory. Should we document the Windows features needed to run hwc.exe? Looks like that is definitely missing from a README

**Comment by sunjayBhatia** [comment] 2017-04-11 02:16
@sneal given that https://github.com/cloudfoundry-incubator/hwc/pull/2 was merged, can we close this out? Anything else you think we should add to the documentation?

**Comment by aminjam** [comment] 2017-04-11 11:54
@sunjayBhatia We still need to find a way to throw an error for when the windows features are missing. I suspect [checking for the missing DLLs](https://github.com/cloudfoundry-incubator/hwc/blob/master/config.go#L147-L182) would solve this problem if the syscall is not returning an error.

**Comment by sunjayBhatia** [comment] 2017-04-19 17:27
@sneal if you take a look at the latest release: https://github.com/cloudfoundry-incubator/hwc/releases/tag/3.0.0 we made some changes to check for DLLs that are required in the `globalModules` section of the `applicationHost.config` we generate.

We ran through the steps you mentioned to reproduce the error and now `hwc.exe` does not fail silently if you are missing any of the required Windows features. If you install the listed Windows features in the README, `hwc.exe` will function as expected.

Does this sound like the proper resolution to this issue/do you have any more feedback?

**Comment by sneal** [comment] 2017-04-20 22:07
@sunjayBhatia Sounds spot on! :shipit:

**Comment by sunjayBhatia** [comment] 2017-04-20 22:08
@sneal awesome, thanks for helping us improve this

**Closed by sunjayBhatia** 2017-04-20 22:08 UTC
Labels: delivered
